nest/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy


# DB handler
db = SQLAlchemy()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    picture = db.Column(db.String(120))
    first_name = db.Column(db.String(120))

    def __init__(self, username, email, picture, first_name):
        self.username = username
        self.email = email
        self.picture = picture
        self.first_name = first_name

    def __repr__(self):
        return '<User %r>' % self.username

nest/__init__.py
from werkzeug.exceptions import BadRequest
from flask import Flask, render_template
from flask_debugtoolbar import DebugToolbarExtension
import os
from .login import login
from .home import home
from .models import db

app = Flask(__name__)
app.config.from_object(os.environ['app.settings'])

# Init extensions
db.init_app(app)
toolbar = DebugToolbarExtension(app)

# Load login blueprint
app.register_blueprint(login)
app.register_blueprint(home)

with app.app_context():
    app.logger.info("Loading database schema")
    db.create_all()


@app.errorhandler(BadRequest)
def handle_bad_request(e):
    return 'bad request!' % e


@app.errorhandler(404)
def error404(error):
    return render_template("notfound.html", error=error), 404

nest/home/__init__.py
from flask import Blueprint
from flask_boto3 import Boto3

home = Blueprint(
    'home',
    __name__,
    template_folder='templates',
    static_folder='static'
)

boto = Boto3()


@home.record_once
def on_load(state):
    boto.init_app(state.app)

from . import views  # noqa

nest/home/views.py
from flask import render_template, redirect, request,\
    flash, current_app, url_for
from werkzeug.utils import secure_filename

from . import boto, home
from .utils import allowed_file
from flask_login import login_required


@home.route('/')
@login_required
def index():
    return render_template("index.html")


@home.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            boto.clients['s3'].put_object(
                ACL='public-read',
                Bucket=current_app.config['S3_BUCKET'],
                Key=filename,
                Body=file,
            )
            flash("Your file has been uploaded successfully!")
            return redirect(url_for('home.list_uploaded_files'))
        else:
            flash("This type of file is forbidden.")
            return redirect(request.url)
    else:
        return render_template('index.html')


@home.route('/delete/<name>')
@login_required
def delete_file(name):
    boto.clients['s3'].delete_object(
        Bucket=current_app.config['S3_BUCKET'],
        Key=name
    )
    flash("File %s was deleted" % name)
    return redirect(url_for('home.list_uploaded_files'))


@home.route('/uploads')
@login_required
def list_uploaded_files():
    contents = boto.clients['s3'].list_objects_v2(
        Bucket=current_app.config['S3_BUCKET']
    )
    return render_template('uploaded.html', contents=contents)

nest/login/__init__.py
from flask import Blueprint
from flask_login import LoginManager
from authomatic import Authomatic


login_manager = LoginManager()
login = Blueprint(
    'login',
    __name__,
    template_folder='templates',
    static_folder='static'
)


@login.record_once
def on_load(state):
    login_manager.init_app(state.app)
    state.app.authomatic = Authomatic(
        state.app.config['AUTHOMATIC'],
        secret=state.app.secret_key
    )


from . import views  # noqa

nest/login/views.py
from authomatic.adapters import WerkzeugAdapter
from flask import render_template, redirect, url_for, \
    make_response, request, session, current_app, flash
from flask_login import login_required, logout_user, login_user
from . import login_manager, login
from nest.models import db, User


@login_manager.user_loader
def load_user(user_id):
    """
    Retrieves a use from database
    Args:
        user_id: ID of user to retrieve

    Returns: User

    """
    return User.query.filter_by(id=user_id).first()


@login_manager.unauthorized_handler
def unauthorized():
    # do stuff
    return render_template('forbidden.html')


@login.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have been disconnected!")
    return redirect(url_for('home.index'))


@login.route('/login', methods=['GET', 'POST'])
def login():
    response = make_response()
    result = current_app.authomatic.login(
        WerkzeugAdapter(request, response),
        provider_name='google',
        session=session,
        session_saver=lambda: current_app.save_session(session, response)
    )

    # If there is no LoginResult object, the login procedure is still pending.
    if result:
        if result.user:
            # We need to update the user to get more info.
            result.user.update()
            user = User.query.filter_by(email=result.user.email).first()
            if user is None:
                user = User(email=result.user.email,
                            username=result.user.email.split('@')[0],
                            picture=result.user.picture,
                            first_name=result.user.first_name)
                db.session.add(user)
                db.session.commit()
            login_user(user, remember=True)

        # The rest happens inside the template.
        flash("Welcome %s!" % result.user.name)
        return redirect(url_for('home.index'))

    # Don't forget to return the response.
    return response

nest/routes.py
from flask import render_template, flash, redirect
from flask import url_for, request
from flask_login import login_required
from werkzeug.utils import secure_filename
from . import app, boto_flask
from .utils import allowed_file


@app.route('/')
def index():
    return render_template("index.html")


@app.route('/upload', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            boto_flask.clients['s3'].put_object(
                ACL='public-read',
                Bucket=app.config['S3_BUCKET'],
                Key=filename,
                Body=file,
            )
            flash("Your file has been uploaded successfully!")
            return redirect(url_for('list_uploaded_files'))


@app.route('/delete/<name>')
def delete_file(name):
    boto_flask.clients['s3'].delete_object(
        Bucket=app.config['S3_BUCKET'],
        Key=name
    )
    flash("File %s was deleted" % name)
    return redirect(url_for('list_uploaded_files'))


@app.route('/uploads')
@login_required
def list_uploaded_files():
    contents = boto_flask.clients['s3'].list_objects_v2(
        Bucket=app.config['S3_BUCKET']
    )
    return render_template('uploaded.html', contents=contents)

nest/home/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="col s8 offset-s2">
        <form method="POST" action="{{ url_for('home.upload_file') }}" enctype="multipart/form-data">
        <div class="card horizontal">
            <div class="card-image">
                <img src="http://lorempixel.com/100/190/nature/6">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <p>Please provide a file with one of these extensions: {{ config['ALLOWED_EXTENSIONS']| join(', ') }}</p>
                    <p>
                        <div class="file-field input-field">
                          <div class="btn">
                            <span>File</span>
                            <input type="file" name="file" required>
                          </div>
                          <div class="file-path-wrapper">
                            <input class="file-path validate" required type="text" placeholder="Upload one or more files">
                          </div>
                        </div>
                        <div class="input-field">
                            <label for="expiry" style="display: none;">Expiration</label>
                            <select name="expiry" id="expiry">
                              <option value="" disabled selected>Please select file expiration</option>
                              <option value="1">No expiration</option>
                              <option value="2">After 1 week</option>
                              <option value="3">After 1 month</option>
                              <option value="3">After 1 year</option>
                            </select>
                            <label>Expiration</label>
                        </div>
                </div>
                <div class="card-action align-right">
                    <button type="submit" class="waves-effect waves-teal btn-flat">
                    Envoyer <i class="material-icons right">send</i>
                </button>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock content %}

nest/home/templates/uploaded.html
{% extends 'base.html' %}
{% block content %}
<ul class="collection with-header">
<li class="collection-header"><h4>My files</h4></li>
{% for item in contents.Contents %}
<li class="collection-item">
    <div>{{ item.Key }}<a href="{{ url_for("home.delete_file", name=item.Key) }}" class="secondary-content"><i class="material-icons">delete</i></a></div>
</li>
    {% else %}
    <li class="collection-item">You don't have any files stored. You can <a href="{{ url_for('home.index') }}">upload one</a>.</li>
{% endfor %}
</ul>
{% endblock content %}

nest/login/templates/forbidden.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col s6 offset-s3">
          <div class="card white">
            <div class="card-content">
              <span class="card-title">Authentication required</span>
              <p>In order to use this application, you must be signed-in using your Google account.</p>
            </div>
            <div class="card-action">
              <a href="{{ url_for('login.login') }}">Sign in</a>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

nest/login/templates/login.html
{# index.html #}
{% extends "base.html" %}

{% block content %}

    <a href="/">Home</a>

    {# Check for errors. #}
    {% if result.error %}
        <h2>Damn that error: {{ result.error.message }}</h2>
    {% endif %}

    {# Welcome the user. #}
    {% if result.user %}
        <h1>Hi {{ result.user.name }}</h1>
        <h2>Your id is: {{ result.user.id }}</h2>
        <h2>Your email is: {{ result.user.email }}</h2>
    {% endif %}

    {# If the user has credentials, we can access his/her protected resources. #}
    {% if result.user.credentials %}

        {# Let's get the user's 5 most recent statuses. #}
        {% if result.provider.name == 'fb' %}
            Your are logged in with Facebook.<br />

            {# Insert the user's ID to the URL and access the resource. #}
            {% set url = 'https://graph.facebook.com/{0}?fields=feed.limit(5)'.format(result.user.id) %}
            {% set response = result.provider.access(url) %}

            {# Parse the response. #}
            {% if response.status == 200 %}

                {% if response.data.error %}
                    Damn that error: {{ response.data.error }}!
                {% endif %}

                {% if response.data.feed.data %}
                    Your 5 most recent statuses:<br />

                    {% for status in response.data.feed.data %}
                        <h3>{{ status.message or status.name or status.story }}</h3>
                        Posted on: {{ status.created_time }}
                    {% endfor %}
                {% endif %}

            {% endif %}{# response.status == 200 #}

        {% endif %}{# result.provider.name == 'fb' #}

        {# Do the same for Twitter. #}
        {% if result.provider.name == 'tw' %}
            Your are logged in with Twitter.<br />

            {% set url = 'https://api.twitter.com/1.1/statuses/user_timeline.json?count=5' %}
            {% set response = result.provider.access(url) %}

            {% if response.status == 200 %}

                {% if response.data.errors %}
                    Damn that error: {{ response.data.errors }}!
                {% endif %}

                {% if response.data %}
                    Your 5 most recent tweets:<br />

                    {% for tweet in response.data %}
                        <h3>{{ tweet.text }}</h3>
                        Posted on: {{ tweet.created_at }}
                    {% endfor %}
                {% endif %}

            {% endif %}

        {% endif %}{# result.provider.name == 'tw' #}
    {% endif %}{# result.user.credentials #}

{% endblock content %}

nest/templates/_header.html
<header>
    <nav class="transparent z-depth-0">
        <div class="nav-wrapper">
            <a href="{{ url_for("home.index") }}" class="brand-logo center">Nest</a>
            <a href="#" data-activates="slide-out" class="button-collapse hide-on-large"><i class="material-icons">menu</i></a>
            {% if current_user.is_authenticated %}
            <ul class="right hide-on-med-and-down">
                <li><a href="{{ url_for("home.index") }}"><i class="material-icons left">cloud_upload</i>Send a file</a></li>
                <li><a href="{{ url_for("home.list_uploaded_files") }}"><i class="material-icons left">folder_open</i>My files</a></li>
                <li>
                    <a href="{{ url_for('login.logout') }}" title="Logout">
                        <i class="material-icons right">power_settings_new</i>
                        {{ current_user.first_name }}</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>
</header>
{% include '_sidenav.html' %}

nest/templates/_sidenav.html
<ul id="slide-out" class="side-nav">
    <li><div class="userView" style="min-height: 10em;">
      <div class="background">
        <img src="{{ url_for('static', filename='images/office.jpg') }}">
      </div>
        {% if current_user.is_authenticated %}
      <a><img class="circle" src="{{ current_user.picture }}"></a>
      <a><span class="white-text name">{{ current_user.username }}</span></a>
      <a><span class="white-text email">{{ current_user.email }}</span></a>
        {% endif %}
    </div></li>
    {% if current_user.is_authenticated %}
        <li><a href="{{ url_for("home.index") }}"><i class="material-icons">cloud_upload</i>Upload a file</a></li>
        <li><a href="{{ url_for("home.list_uploaded_files") }}"><i class="material-icons">folder_open</i>My files</a></li>
        <li><div class="divider"></div></li>
        <li><a href="{{ url_for('login.logout') }}"><i class="material-icons">power_settings_new</i>Logout</a></li>
    {% else %}
        <li><a href="{{ url_for('login.login') }}"><i class="material-icons">power_settings_new</i>Login</a></li>
    {% endif %}
  </ul>

nest/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nest</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

</head>
<body>
{% include '_header.html' %}
<main class="container">
    {% block content %}
    <div class="row">

    <div class="col s8 offset-s2">
        <div class="card horizontal">
            <div class="card-image">
                <img src="http://lorempixel.com/100/190/nature/6">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
    </div>

    </div>
    {% endblock content %}
</main>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
<script src="{{ url_for('static', filename='main.js') }}"></script>
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
        <script type="text/javascript">
        Materialize.toast("{{ message }}", 4000)
        </script>
    {% endfor %}
  {% endif %}
{% endwith %}
</body>
</html>

nest/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="col s8 offset-s2">
        <form method="POST" action="{{ url_for('upload_file') }}" enctype="multipart/form-data">
        <div class="card horizontal">
            <div class="card-image">
                <img src="http://lorempixel.com/100/190/nature/6">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information.</p>
                    <p>
                        <div class="file-field input-field">
                          <div class="btn">
                            <span>File</span>
                            <input type="file" name="file">
                          </div>
                          <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                          </div>
                        </div>
                    </p>
                </div>
                <div class="card-action align-right">
                    <button type="submit" class="waves-effect waves-teal btn-flat">
                    Envoyer <i class="material-icons right">send</i>
                </button>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock content %}

nest/templates/notfound.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col s6 offset-s3">
          <div class="card white">
            <div class="card-content">
              <span class="card-title">Page not found</span>
              <p>The page you requested was not found. You can try to <a href="javascript:history.go(-1);">go back</a>
              or to the <a href="{{ url_for('home.index') }}">homepage</a>.</p>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}